name: Build Mac OS
on:
  workflow_call:
    inputs:
      sc-version:
        required: true
        type: string

jobs:
  build-macos:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - filename: build_macos_universal.yml
          - filename: build_macos_x64_shared-libscsynth.yml
          - filename: build_macos_x64_use-system-libraries.yml
          - filename: build_macos_x64-legacy.yml

    name: macOS ${{ matrix.filename }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # uses can't reference matrix variables, so we use
      # a static if condition check
      - name: Start macOS universal build
        if: matrix.filename == 'build_macos_universal.yml'
        uses: ./.github/workflows/build_macos_universal.yml
        with:
          sc-version: ${{ inputs.sc-version }}

      - name: Start macOS x64 shared libscsynth build
        if: matrix.filename == 'build_macos_x64_shared-libscsynth.yml'
        uses: ./.github/workflows/build_macos_x64_shared-libscsynth.yml
        with:
          sc-version: ${{ inputs.sc-version }}

      - name: Start macOS x64 system libraries build
        if: matrix.filename == 'build_macos_x64_use-system-libraries.yml'
        uses: ./.github/workflows/build_macos_x64_use-system-libraries.yml
        with:
          sc-version: ${{ inputs.sc-version }}

      - name: Start macOS x64 legacy build
        if: matrix.filename == 'build_macos_x64-legacy.yml'
        uses: ./.github/workflows/build_macos_x64-legacy.yml
        with:
          sc-version: ${{ inputs.sc-version }}

