name: Build Mac OS MacPorts
on:
  workflow_call:
    inputs:
      sc-version:
        required: true
        type: string

jobs:
  build-macos-macports:
    runs-on: macos-12
    name: macOS MacPorts build
    env:
      BUILD_PATH: ${{ github.workspace }}/build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: melusina-org/setup-macports@v1
        name: Setup dependencies via macPorts
      
      - name: Install dependencies
        run: port install portaudio libsndfile readline fftw-3 qt5 qt5-qtwebengine qt5-qttools

      - name: configure
        run: |
          mkdir $BUILD_PATH && cd $BUILD_PATH
          # add macdeployqt to PATH
          export PATH="/opt/local/libexec/qt5/bin:$PATH"
          cmake -G"Xcode" -DSUPERNOVA=ON ..

      - name: build
        run: cmake --build $BUILD_PATH --config Release --target install
